---
apiVersion: v1
kind: Secret
metadata:
  name: long12345678901234567890-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/long12345678901234567890-gateway-gitops
